import { ConflictException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma, SalesCredentialStatus, SalesIntegrationStatus } from "@prisma/client";
import { PrismaService } from "../../platform/database/prisma.service";
import { IntegrationSecretService } from "../../security/integration-secret.service";
import { SalesCredentialDto, SalesIntegrationStatusDto, UpsertSalesIntegrationDto } from "./dto/sales-integration.dto";

@Injectable()
export class SalesIntegrationService {
  constructor(private readonly prisma: PrismaService, private readonly secrets: IntegrationSecretService) {}
  list(tenantId: string) { return this.prisma.salesIntegration.findMany({ where: { tenantId }, include: { credentials: { where: { status: SalesCredentialStatus.ACTIVE }, take: 1 } }, orderBy: { createdAt: "desc" } }).then((rows) => rows.map((row) => this.view(row))); }
  async get(tenantId: string, id: string) { const row = await this.find(tenantId, id); return this.view(row); }
  async create(tenantId: string, userId: string, dto: UpsertSalesIntegrationDto) { const row = await this.prisma.salesIntegration.create({ data: { tenantId, createdByUserId: userId, updatedByUserId: userId, provider: dto.provider, channel: dto.channel, displayName: dto.displayName, externalMerchantId: dto.externalMerchantId, settings: (dto.settings ?? {}) as Prisma.InputJsonValue }, include: { credentials: true } }); return this.view(row); }
  async update(tenantId: string, userId: string, id: string, dto: UpsertSalesIntegrationDto) { await this.find(tenantId, id); const row = await this.prisma.salesIntegration.update({ where: { id }, data: { displayName: dto.displayName, externalMerchantId: dto.externalMerchantId, settings: (dto.settings ?? {}) as Prisma.InputJsonValue, updatedByUserId: userId }, include: { credentials: { where: { status: SalesCredentialStatus.ACTIVE }, take: 1 } } }); return this.view(row); }
  async rotateCredential(tenantId: string, userId: string, id: string, dto: SalesCredentialDto) { await this.find(tenantId, id); await this.prisma.$transaction(async (tx) => { await tx.salesIntegrationCredential.updateMany({ where: { tenantId, integrationId: id, status: SalesCredentialStatus.ACTIVE }, data: { status: SalesCredentialStatus.ROTATED, rotatedAt: new Date() } }); await tx.salesIntegrationCredential.create({ data: { tenantId, integrationId: id, credentialType: "PAGBANK_EDI_TOKEN", secretCiphertext: this.secrets.encrypt(dto.token), fingerprint: this.secrets.fingerprint(dto.token), createdByUserId: userId } }); }); }
  async setStatus(tenantId: string, userId: string, id: string, dto: SalesIntegrationStatusDto) { const row = await this.find(tenantId, id); if (dto.status === "ACTIVE" && (!row.externalMerchantId || row.credentials.length === 0)) throw new ConflictException("USER e TOKEN sao obrigatorios para ativar"); const updated = await this.prisma.salesIntegration.update({ where: { id }, data: { status: dto.status as SalesIntegrationStatus, updatedByUserId: userId }, include: { credentials: { where: { status: SalesCredentialStatus.ACTIVE }, take: 1 } } }); return this.view(updated); }
  async getCredential(tenantId: string, id: string) { const row = await this.find(tenantId, id); const credential = row.credentials[0]; if (!credential) throw new ConflictException("Credencial PagBank ausente"); return { integration: row, token: this.secrets.decrypt(credential.secretCiphertext) }; }
  private async find(tenantId: string, id: string) { const row = await this.prisma.salesIntegration.findFirst({ where: { id, tenantId }, include: { credentials: { where: { status: SalesCredentialStatus.ACTIVE }, take: 1 } } }); if (!row) throw new NotFoundException("Integracao nao encontrada"); return row; }
  private view(row: Prisma.SalesIntegrationGetPayload<{ include: { credentials: true } }>) { const credential = row.credentials.find((item) => item.status === SalesCredentialStatus.ACTIVE); return { id: row.id, provider: row.provider, channel: row.channel, status: row.status, displayName: row.displayName, externalMerchantId: row.externalMerchantId, settings: row.settings, hasCredential: Boolean(credential), credentialFingerprint: credential?.fingerprint ?? null, lastValidationAt: row.lastValidationAt?.toISOString() ?? null, lastErrorCode: row.lastErrorCode, lastErrorMessage: row.lastErrorMessage, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() }; }
}
